---
title: "ETC5242Assignment"
author: "Sahinya Akila"
date: "9/4/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
## Remove the line break in the file name!
churn_dat <- read_csv("https://raw.githubusercontent.com/square/pysurvival/master/pysurvival/datasets/churn.csv")
churn_dat <- churn_dat %>% filter(months_active > 0) %>% select(c(months_active, churned, company_size))
```

```{r}
km_model <- function(time, event){
  dataset <- data_frame(time, event)
  
  km_data <- dataset %>% 
    group_by(time, event) %>% 
    summarise(died = n()) %>% 
    ungroup() %>% 
    mutate(risk = nrow(dataset) - accumulate(died, `+`) + died) %>% 
    filter(event == 1) %>% 
    mutate(probability = 1 - died/risk,
           survival = accumulate(probability, `*`))
  return(km_data %>% select(time, survival))
}

km_survive <- km_model(churn_dat$months_active, churn_dat$churned) 

km_survive %>% 
  ggplot(aes(time, survival)) +
  geom_step()
```


```{r}
company_km_model <- data.frame(time = double(), survival = double(), company_size = character())
for(size in unique(churn_dat$company_size)){
  filtered <- churn_dat %>% filter(company_size == size)
  final_model <- km_model(filtered$months_active, filtered$churned) %>% mutate(company_size = size)
  company_km_model <- rbind(company_km_model, final_model)
}

company_km_model %>% 
  ggplot(aes(time, survival)) +
  geom_step() +
  facet_wrap(~company_size)
```

Q2

- Compute the Kaplan-Meir curve and use this to estimate the median churn time

```{r}
library(survival)
fit <- survfit(Surv(months_active, churned) ~ 1, data = churn_dat)
event_times <- fit$time
kaplan_meier <- fit$surv
```

```{r}
median(Surv(churn_dat$months_active, churn_dat$churned))
```

```{r}
sd(Surv(churn_dat$months_active, churn_dat$churned))
```
Use a non-parametric bootstrap to construct 90% confidence intervals for the median of each company size

```{r}
summary(fit)
```

```{r}
y = rnorm(nrow(churn_dat), mean = mean(churn_dat$months_active), sd = sd(churn_dat$months_active))
bootstrap <- tibble(experiment = rep(1:10000, each = 100),
ind = sample(1:100, size = 100*10000, replace = TRUE),
ystar = y[ind])
bias <- bootstrap %>%
group_by(experiment) %>%
summarise(delta = median(y) - median(ystar))
median(y) + quantile(bias$delta, c(0.05, 0.95)) 
```


```{r}
companysize <- c("self-employed", "1-10", "10-50", "50-100", "100-250")
comp_boot <- function(companysize) { 
  comp_data <- churn_dat %>% 
    filter(company_size == companysize) 
y = rnorm(nrow(comp_data), mean = mean(comp_data$months_active), sd = sd(comp_data$months_active)) 
bootstrap <- tibble(experiment = rep(1:10000, each = 100),
ind = sample(1:100, size = 100*10000, replace = TRUE),
ystar = y[ind])
bias <- bootstrap %>%
group_by(experiment) %>%
summarise(delta = median(y) - median(ystar))
median(y) + quantile(bias$delta, c(0.05, 0.95), na.rm = TRUE) 
  
}
a2 = map(companysize, comp_boot)
a2
```


Make a plot that shows that estimate of the median and the corresponding confidence interval on the
same axes

```{r}
fit1 <- survfit(Surv(months_active, churned) ~ company_size, data = churn_dat)
event_times <- fit$time 
kaplan_meier <- fit$surv 

summary(fit1)

```

```{r}
library(survminer)
library(ggplot2)
ggsurvplot(fit1, conf.int = TRUE, pval = TRUE) 
```

