---
title: "Untitled"
author: "Sahinya Akila"
date: "9/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purr)
```



```{r}
churn_dat <- read_csv("https://raw.githubusercontent.com/square/pysurvival/master/pysurvival/datasets/churn.csv")
churn_dat <- churn_dat %>% filter(months_active > 0)

```

```{r}
q1 <- churn_dat %>% 
  #filter(us_region == "West North Central") %>% 
  group_by(months_active,churned) %>% 
  summarise(count = n()) %>% 
  mutate(total_count = sum(count)) %>% 
  ungroup() %>% 
  mutate(total_count = ifelse(churned==0,0, total_count),
         cumulative=cumsum(total_count),
         cumulative=ifelse(churned==0,0, cumulative)) %>% 
           ungroup() %>% 
  mutate(jf=1958-cumulative,
         jf=ifelse(churned==0,0, jf)) %>% 
  mutate(count2=ifelse(churned==0,0, count),
         hazard=count2/jf,
          prsurvival=1-hazard,
         prsurvival=ifelse(churned==0,1, prsurvival),
         surv=cumprod(prsurvival),
         surv=ifelse(churned==0,0, surv)) %>%  
  arrange(months_active,-churned) 

q1 %>% 
  filter(churned==1) %>% 
  ggplot() + 
  geom_step(mapping = aes(x=months_active,y=surv))
      
```


```{r}
churn_dat1 <- churn_dat %>% 
select(company_size,months_active,churned)
# time = churn_dat$months_active
# event <- churn_dat$churned
q1a <- function(time,event){
  data <- tibble(time,event)
  Total <- nrow(data)
  data1 <- data %>% 
  group_by(time,event) %>% 
  summarise(count = n()) %>% 
  arrange(time,-event) %>% 
  ungroup() %>% 
  mutate(cumulative = cumsum(count)) %>% 
  mutate(jf=1958-cumulative) %>% 
  mutate(jf = jf + count) %>% 
  mutate(count2=ifelse(event==0,0, count),
         pevent=count2/jf,
         prsurvival=1-pevent,
         prsurvival=ifelse(event==0,1, prsurvival),
         surv=cumprod(prsurvival),
         surv1 = surv,
         surv1=ifelse(event==0,0, surv1))
  return(data1)
}
data_q1a <- q1a(churn_dat1$months_active,churn_dat1$churned)
data_q1a %>% 
  ggplot() + 
  geom_step(mapping = aes(x=time,y=surv)) +
  scale_x_discrete(breaks = seq(0,12,1)) +
  scale_y_discrete(breaks = seq(0,1,0.25))

```

```{r}
q1b <- function(time,event,comp_size){
  data <- tibble(comp_size,time,event)
  Total <- nrow(data)
  comp_data <- data %>% 
    group_by(comp_size) %>% 
    summarise(count = n())
  data1 <- data %>% 
  group_by(comp_size,time,event) %>% 
  summarise(count = n()) %>% 
  arrange(time,-event) %>% 
  ungroup() %>%
  group_by(comp_size) %>% 
  mutate(cumulative = cumsum(count)) %>% 
  ungroup() %>% 
  mutate(jf = 0)
  for(i in 1:length(comp_data$comp_size)){
    data1 <- data1 %>% 
      group_by(comp_size) %>% 
      mutate(jf = ifelse(comp_size == comp_data$comp_size[[i]],comp_data$count[[i]]-cumulative,
                        jf))
    i = i + 1 
  }
  data1 <- data1 %>%
    group_by(comp_size) %>% 
    mutate(jf = jf + count) %>% 
    mutate(count2=ifelse(event==0,0, count),
         pevent=count2/jf,
         prsurvival=1-pevent,
         prsurvival=ifelse(event==0,1, prsurvival),
         surv=cumprod(prsurvival),
         surv1 = surv,
         surv1=ifelse(event==0,0, surv1))
  return(data1)
}
data_q1b <- q1b(churn_dat1$months_active,churn_dat1$churned,churn_dat$company_size)
data_q1b %>% 
filter(event==1) %>% 
  ggplot() + 
  geom_step(mapping = aes(x=time,y=surv)) +
  scale_x_discrete(breaks = seq(0,12,1)) +
  scale_y_discrete(breaks = seq(0,1,0.25)) +
  facet_wrap(~comp_size)
```



